### ISSUE TITLE
System demo returns 400 (and Flask debug screen)

### ISSUE THREAD

**Issue by mrshu** [UKPLab/acl2021-metaphor-generation-conceptual#1]
Hello everyone,

Thank you for your interesting work!

When testing out your system's demo at http://metaphorgenerator.cs.columbia.edu:8080/ with the sentence `The car drove up alongside him`, I received 400 error (see attached image). Seems like something must have changed, as the `other` field item is no longer to be found in the request.

Let me know if I can be of more help. Thanks!

![2021-07-26_01-15](https://user-images.githubusercontent.com/461491/126916470-e460496c-c56c-4793-a54f-07acfc5c75e6.png)

**Comment by tuhinjubcse** [comment]
![image](https://user-images.githubusercontent.com/3104771/127147656-4759e371-d79c-45fe-b499-f96cffa80ef8.png)
We've restarted the system and it seems to be working now - let us know if you have any issues still.

Thanks for your interest in our work

**Comment by kevincstowe** [comment]
After some testing, it seems that these issues keep popping up - we're looking into it, thanks for your patience!

**Comment by mrshu** [comment]
Awesome, thanks you both! (I sadly was not able to reach it in a working state yet)

**Comment by mrshu** [comment]
Hi @tuhinjubcse and @kevincstowe, it does seem to work now -- thanks a lot for taking a look and for putting this together!

(I'd be very eager to get my hands on the actual model but I am happy to wait until the end of ACL for that :))

**Comment by tuhinjubcse** [comment]
Thank you @mrshu. The model checkpoint is already shared. Feel free to use it
