### ISSUE TITLE
Hi, excellent work! It seems that all data/model download links are not exits anymore. Please check.

### ISSUE THREAD

**Issue by liyucheng09** [UKPLab/acl2021-metaphor-generation-conceptual#3]

**Comment by kevincstowe** [comment]
Apologies for the delay, we're working on solutions for permanent hosting now. We will have stable links soon!

UPDATE: I've reuploaded the files to the drive, and reattached the links, so they should work for now. Still working on a stable solution which should be ready soon, but the links should work at the moment. Let me know if you have any issues.

**Comment by liyucheng09** [comment]
@kevincstowe Thanks for your quick responds. I sent an application for access permission. Please pass it.
